### ISSUE TITLE
Configure the multiple files or single file

### ISSUE THREAD

**Issue by channaitfac** [pfbrowning/ng-file-drop#1]
Is there any configuration option for allowing to multiple files or single file.
Thanks in advance.

**Comment by pfbrowning** [comment]
No, this component currently only supports multiple files.  Since the component logic is based on an array of selected files, I think that the best way to implement this would be to implement a maxFiles integer input property, rather than a single / multiple file switch.

I think that this is a good idea, but it's a pretty low priority for me right now.  I'd welcome pull requests if somebody wants to implement this.
